Exercise 1

In [2]:
import numpy as np

In [3]:
def vander_matrix(vector, N, increasing = False):
    if not increasing:
        matrix = np.array([x**(N-1-i) for x in vector for i in range(N)]).reshape(vector.size,N)
    else:
        matrix = np.array([x**i for x in vector for i in range(N)]).reshape(vector.size,N)
    return matrix

In [6]:
vector = np.array([1, 2, 3, 5])
N = 3
matrix_desc = vander_matrix(vector,N,False)
matrix_inc = vander_matrix(vector,N,True)

In [8]:
matrix_desc

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [7]:
matrix_inc

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

Exercise 2

In [12]:
def mov_average(x, n):
    xsum = np.cumsum(x, dtype=float)
    xsum[n:] = xsum[n:] - xsum[:-n]
    return xsum[n-1:]/n

In [13]:
x =  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [14]:
x_arr = np.array(x)

In [15]:
np.array(mov_average(x_arr, 3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])